In [1]:
import torch
import numpy as np

D:\anaconda\envs\pytorch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
t=torch.tensor([1,2])
print(t)
print(t.dtype)

tensor([1, 2])
torch.int64


In [3]:
t=torch.FloatTensor([1,2])
print(t)
print(t.dtype)

tensor([1., 2.])
torch.float32


In [4]:
t=torch.LongTensor([[1,2],[3,4]])
print(t)
print(t.dtype)

tensor([[1, 2],
        [3, 4]])
torch.int64


In [6]:
np_array=np.array([[1,2],[3,4]])
t_np=torch.from_numpy(np_array)
print(t_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [7]:
t=torch.tensor([1,2],dtype=torch.float32)
print(t)
print(t.dtype)
t=torch.tensor([1,2],dtype=torch.float)
print(t.dtype)
print(torch.float==torch.float32)
print(torch.long==torch.int64)

tensor([1., 2.])
torch.float32
torch.float32
True
True
